package main

import "github.com/Luzifer/rconfig"

type configuration struct {
	EnableCache     bool   `flag:"cache" default:"true" description:"Enable S3 caching of autogenerated version"`
	Bucket          string `flag:"bucket" default:"" description:"S3 bucket for saving cache to"`
	RefreshInterval int    `flag:"refresh" default:"12" description:"Time in hours to refresh from Mozilla source"`
}

func loadConfig() *configuration {
	c := &configuration{}
	rconfig.Parse(c)

	return c
}
